### ISSUE TITLE
Redundant Cassini mission phases

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#1339]
The Cassini Mission Phases "Equinox Mission" and "Solstice Mission" have zero search results. They have probably been superceded by things like "Extended Mission" and should be removed from the available options.

**Comment by matthewtiscareno** [comment]
Firstly, the problem statement is not true.  See attached screenshot.  It seems that every value of Cassini Mission Phase has an instance somewhere in the holdings. 
![Screen Shot 2024-01-23 at 2 28 46 PM](https://github.com/SETI/rms-opus/assets/18727430/1f498415-5a7e-499b-97c3-3550cb0e5d16)

Secondly, the Cassini LDD has multiple synonymous values for `mission_phase_name`.  I strongly disagree with this design decision, but Atmospheres Node are the stewards of this LDD and it was their decision.  Basically, different instrument teams used different names for the same thing, and they decided to change the standards to fit the data rather than the other way around.  For example, "Equinox Mission" and "Extended Mission" are synonymous with each other, as are "Solstice Mission" and "Extended-Extended Mission."  

It would be best (but is not urgent) for us to eliminate synonymous values of this attribute.  For example, I would prefer we use the ones you mention and remove the ones with "Extended" in the name.

**Comment by matthewtiscareno** [comment]
I'm realizing that my response here is adding some PDS4 concepts to the conversation, while you are talking about a strictly PDS3 situation.  Nevertheless, I think my basic points remain valid.

**Comment by rfrenchseti** [comment]
Sorry, this was user error. I was looking only at Cassini ISS, which inadvertently revealed the exact issue you brought up.

Note this has nothing to do with the LDD, since this is a PDS3 data set.

Perhaps when we convert to importing the PDS4 version we can map the mission phase names as you suggest.

**Comment by matthewtiscareno** [comment]
Yes, this is PDS3.  However, it's interesting to note that the LDD has been set up in such a way that this problem will be perpetuated in PDS4. 

Yes, we could do that.  In fact, nothing prevents us from going ahead now with a mapping as part of the OPUS import.  However, as I said, it's not a priority.
