### ISSUE TITLE
Sort on multiple fields

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#362]
Currently it's possible to sort on a single field by using the "view table" view and clicking on a column header. However, there are times you want to sort on multiple columns, since columns like "planet" or "mission" can have a large number of entries that are all identical. For example, you might want to sort on "Target Body" in ascending order, then on "Filter" in ascending order, then on "Observation Duration" in descending order.

The JPL Imaging Node "Image Atlas" allows this kind of searching. We should too.

**Comment by rfrenchseti** [comment]
Implementation ideas:

- In both the gallery and table views, there should be an indication of the current sort order at the top.
- The current sort order can have multiple entries, in order, each indicating a slug and an order (ascending, descending).
- Sort order elements can be removed by clicking on an "x" next to them, sort of like "filter results" on shopping web sites.
- New sort order elements can be added by selecting them from a dropdown menu that contains all the available slugs, just like "choose columns".

**Comment by rfrenchseti** [comment]
Agreed to implement BYBTW 2/6/2020

**Comment by dstopp** [comment]
Implementation details:
-drag the sort pills to change the sort order
-add '+' to the right of the last sort pill <responsiveness>
-the '+' will drop down a simple list of columns that we have already selected to display
-change the functionality so that OPUS id is not always displayed or in the URL if the user did not add it <change normalizeURL to not add OPUS id on to the end of sort>
-Allow user to remove all sort pills; thus all sort pills can have an X.
	Create 'gray' text in the sort pill area that indicates that the default sort order is OPUS id. 
-add tiny numeric order indicator (icon) to the right of the table header to indicate the order of sort <when there are 2 or more user selected sort, not including OPUS id>
-click on an unselected marker will maintain same behavior as current <replace current sort>; ctrl click will append selected column to end of sort
-click or ctrl click on a selected marker <same behavior for both> will change the sort direction for that column
-take care of responsiveness issues as more pills get added <suggested to make that a scroll area>
-if a selected column is removed that was in the sort order, the data will continue to be sorted on that column and the pill will remain visible.
 <note that means there may be things in the pill list that do not have sort headers>
