### ISSUE TITLE
API HTML return exposes internals of OPUS

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#377]
Right now the HTML return is really only useful for the OPUS UI, because it has specific classes and templates that we use. It's not very generic and useful to third parties. We should either stop advertising HTML to the public, or supply prettier HTML to the public and reserve the specialized version for internal use using some magic flag to indicate it.

**Comment by juzen2003** [comment]
Test has been run against the dev server to check the actual supported return format for each API. Attached file is the log (The test would print out error message only when documented and actual supported format didn't matched.) I think we can remove zip format since none of API has valid response when return format is zip. For html, I think we could also get rid of it because some of return html is not very useful, like this one: http://dev.pds-rings.seti.org/opus/api/meta/range/endpoints/wavelength1.html?planet=Earth&target=Moon&limit=2, it would return blank dl tag of html which is not useful at all. If it's approved, I would update the return format in API document corresponding.

[20181114_dev_return_format_testing_log.log](https://github.com/SETI/pds-opus/files/2583331/20181114_dev_return_format_testing_log.log)

**Comment by rfrenchseti** [comment]
I agree about removing .zip as a valid format. We have to be more careful with HTML because some of the HTML returns are actually used by the OPUS UI. We need to figure out which ones are used, and which ones (if any) we want to continue to make public. Then we can remove the public ones we don't want while still supporting the internal ones.

**Comment by rfrenchseti** [comment]
HTML is now fixed for result_count, endpoints, mults, and metadata/opusid.

**Comment by rfrenchseti** [comment]
HTML is now fixed for api/data.html.

Remaining:
fields
image
images

**Comment by rfrenchseti** [comment]
Closing to consolidate API issues.
