### ISSUE TITLE
Summary of issues related to API and return formats

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-opus#510]
**Here is the summary of issues related to API return formats:**
* **Related issues:** #298 , #376 , #377, #378 , #379 

* **Current supported (verified) formats for each API:**
  * api/data.[fmt]
    * json, html, csv
  * api/metadata/[opus_id].[fmt]
    * json, html
  * api/metadata_v2/[opus_id].[fmt]
    * json, html
  * api/images/[size].[fmt]
    * json, html
  * api/images.[fmt]
    * json, html
  * api/image/[size]/[opus_id].[fmt]
    * json, html
  * api/files/[opus_id].[fmt]
    * json
  * api/files.[fmt]
    * json
  * api/meta/result_count.[fmt]
    * json, html
  * api/meta/mults/[param].[fmt]
    * json, html
  * api/meta/range/endpoints/[param].[fmt]
    * json, html
  * api/categories/[opus_id].json
    * json
  * api/categories.json
    * json
  * api/fields/[field].[fmt]
    * json, html
  * api/fields.[fmt]
    * json, html

* **Modification:**
  * Update guide: correct supported formats for each API is updated, will create a pull request for this.
  * Update code: internal and public APIs would have identical return formats for now, need to discuss and determine the supported formats for both if we would like to separate them.

**Comment by rfrenchseti** [comment]
Here is the list of all external API calls that appear in the Apache logs since 9/12/18 (ignoring the ones from our own test frameworks and from internal SETI and our personal Comcast IPs). These are the APIs and formats we should be sure to keep supporting. Other formats we can probably safely get rid of, although we may still want to keep some of them.

- /opus/api/categories.json
- /opus/api/categories/[opus_id].json
- /opus/api/data.json
- /opus/api/files.json
- /opus/api/files/[opus_id].json
- /opus/api/image/[size]/[opus_id].json
- /opus/api/images.json
- /opus/api/images/[size].json
- /opus/api/images/[size]/[opus_id].json
- /opus/api/metadata/[opus_id].{json,html}   (also metadata_v2)
- /opus/api/meta/result_count.json

**Comment by rfrenchseti** [comment]
Likewise, here are all of the internal API uses. These should be verified as complete by looking at the OPUS JavaScript.

/opus/__api/categories/[opus_id].json
/opus/__api/data.{csv,html,json}
/opus/__api/fields.{html,json}
/opus/__api/fields/[fieldname].{html,json}
/opus/__api/files.json
/opus/__api/image/[size]/[opus_id].json
/opus/__api/images.html
/opus/__api/metadata_v2/[opus_id].html
/opus/__api/meta/mults/[param].json
/opus/__api/meta/range/endpoints/[param].json
/opus/__api/meta/result_count.json

**Comment by rfrenchseti** [comment]
Closing to consolidate API issues.
